sudo: false
language: ruby
cache: bundler
branches:
  only:
    - master

before_install:
  - gem update --system
  - gem install bundler

rvm:
  - 2.4.4

bundler_args: --jobs=7 --retry=3 --without docs debug
script:
  - bundle exec rake build
  - bundle exec rake driver:cycle
